"""Generate the small, one-bit Cicala icons from the polygon-only public SVG.

Run from the repository root: python3 scripts/cicala/generate_logo.py
Uses even-odd scan conversion at 8x resolution, then a 50% coverage threshold.
"""

from pathlib import Path
import math
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
svg = ET.parse(ROOT / "assets/cicala/mark.svg").getroot()
origin_x, origin_y, width, height = map(float, svg.attrib["viewBox"].split())
assert width == height
path = svg.find("{http://www.w3.org/2000/svg}path")
assert path is not None and path.attrib["fill-rule"] == "evenodd"
tokens = re.findall(r"[A-Za-z]|-?\d+(?:\.\d+)?", path.attrib["d"])
polygons = []
polygon = []
i = 0
while i < len(tokens):
    command = tokens[i]
    if command in ("M", "L"):
        if command == "M":
            assert not polygon
        polygon.append((float(tokens[i + 1]), float(tokens[i + 2])))
        i += 3
    else:
        assert command in ("z", "Z") and polygon
        polygons.append(polygon)
        polygon = []
        i += 1
assert not polygon

output = ["// Generated by scripts/cicala/generate_logo.py from assets/cicala/mark.svg.",
          "#pragma once", "#include <cstdint>", "namespace cicala_logo {"]
for size in (32, 36):
    scale = size * 8 / width
    edges = []
    for polygon in polygons:
        points = [((x - origin_x) * scale, (y - origin_y) * scale) for x, y in polygon]
        edges.extend(zip(points, points[1:] + points[:1]))
    coverage = [0] * (size * size)
    for row in range(size * 8):
        y = row + 0.5
        crossings = sorted(x1 + (y - y1) * (x2 - x1) / (y2 - y1)
                           for (x1, y1), (x2, y2) in edges if min(y1, y2) <= y < max(y1, y2))
        assert len(crossings) % 2 == 0
        for left, right in zip(crossings[::2], crossings[1::2]):
            for col in range(max(0, math.ceil(left - 0.5)), min(size * 8, math.ceil(right - 0.5))):
                coverage[(row // 8) * size + col // 8] += 1
    data = []
    for y in range(size):
        for start in range(0, size, 8):
            byte = 255
            for bit in range(8):
                if start + bit < size and coverage[y * size + start + bit] >= 32:
                    byte &= ~(1 << (7 - bit))
            data.append(byte)
    output.append(f"inline constexpr uint8_t mark{size}[] = {{")
    output.extend("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ","
                  for i in range(0, len(data), 16))
    output.append("};")
output.append("}  // namespace cicala_logo")
(ROOT / "src/cicala/CicalaLogoBits.h").write_text("\n".join(output) + "\n")
